### ISSUE TITLE
Strategies

### ISSUE THREAD

**Issue by michaelbeaumont** [jhedev/hashcode#1]
Maybe the problem can be considered as a set of memory allocations? Each drone is a memory block of length `numTurns` and every order is a request for memory.
The fit and length of the allocations would be determined by the drones location, where product is, etc.

Each drone only has to know what its last allocation was and at which turn and location it started, the commands we emit as we go along.

<br/>

As far as bringing product between warehouses with `Unload`, a general strategy could just be to keep the distribution even.

More sophisticated would be to assign each location a closest warehouse and create an `Area`, then check the distribution of orders to `Area`s. Like if one order takes a majority of some product, then ship that product to the warehouse for that `Area` with drones going to that `Area`.

**Comment by jhedev** [comment]
The concept of "memory allocations" seems like a good idea. IMO the main questions are how to model the allocation of memory, i.e. how do different parameters influence the allocation, and how do we optimize the allocation in order to finish as much orders as possible. Would this be equivalent to using as much memory as possible?

**Comment by jhedev** [comment]
Did you see the answer from the best group in our hub on Facebook?

They used a quite simple greedy algorithm (similar to what we wanted to do :D ).:

Go through all orders, wait for a drone to become available, let the drone load all products and deliver the order. That was worth 249k points...

Afterwards they have optimized the order which the orders are processed and optimized the paths of the drones and reached 263k points.

So maybe we're just thinking too complex :D

**Comment by michaelbeaumont** [comment]
Got to 198k :D
Might be better to sort the orders by their size, because each order is equally important, no matter if it has a lot or a few items.

**Comment by jhedev** [comment]
198k with the strategy suggested in the facebook group?

**Comment by michaelbeaumont** [comment]
Just read it, it's similar but not sure if it's identical...

**Comment by michaelbeaumont** [comment]
Say we need to deliver `n` of product `p`, that weighs 1 unit, to target `t`. Then `n` units have to be distributed to the drones.

At the moment it's just the drone(s) `d` closest to `t` (at first warehouses distances aren't taken into account), then the warehouse closest to `d`. Of course, even if `d` is closest to `t` it may have to fly over to warehouse `w`. There might even be a drone at `w`. The algorithm doesn't consider this, it doesn't take the combinations into account.

A clearly better strategy than the current one would be to calculate the drone and warehouse combinations with their total length, i.e. `t `dist` w + w `dist` d`. Take the minimum, pack that drone as full as possible, then sort the combos again (because that drone might appear more than once in the first list, but now it's full), continue until product shipped.

This of course also isn't ideal, because we might unnecessarily use more than one drone.
Say there's a drone that's right next to a warehouse holding `p` closest to `t`. Obviously it's best to use this drone and this warehouse. But what if it's only holding 1 item and `n`=10? Then we need to find 9 units of space.
The next drone might have space for 10 items. It may be a little farther away but perhaps it's better to use one drone instead and leave more free? It's not immediately clear to me how to calculate the cost of that.

**Comment by michaelbeaumont** [comment]
Kinda started to do that strat in loadForLoc`. The way it is now gives worse results, but it's incorrect.
